http_port: 4000
tcp_ip: 127.0.0.1
tcp_port: 8080
tcp_test_timeout: 180
tcp_test_max: 3
debug: true
db_dialect: mysql
db_server: 127.0.0.1:3306
db_user: root
db_password:
db_database: umbrella
salt: sfadfasdf
notice_host: http://localhost